### ISSUE TITLE
Cacher titre

### ISSUE THREAD

**Issue by Davxci** [tagcashdev/hatc-gauge-card#1]
Super carte, est il possible d’ajouter la fonction cacher le titre

merci

**Comment by tagcashdev** [comment]
Hello,

C'est déjà possible avec cette configuration :

`
type: custom:hatc-gauge-card
entity: sensor...
title:
  name: false
  icon: false
`

J'ai ajouter cela dans le readme (il n'y était pas)

Et j'ai également ajouter la possibilité de cacher le titre avec la config suivante :

`
type: custom:hatc-gauge-card
entity: sensor...
title: false
`

En effet, title:false cachais bien le titre mais laissais l'icon d'afficher.
C'est désormais corrigé à partir de la version V0.5.3.2
